NIFTY50 = [
    "TCS", "INFY", "WIPRO", "HCLTECH", "TECHM",
    "ONGC", "NTPC", "POWERGRID", "COALINDIA", "BPCL", "TATAPOWER", "GAIL",
    "MARUTI", "TMCV", "TMPV", "M&M", "EICHERMOT", "HEROMOTOCO", "BAJAJ-AUTO",
    "ASHOKLEY", "TVSMOTOR",
    "JSWSTEEL", "TATASTEEL", "HINDALCO", "JINDALSTEL", "SAIL",
    "SUNPHARMA", "DRREDDY", "CIPLA", "DIVISLAB", "APOLLOHOSP", "LUPIN", "ALKEM",
    "HINDUNILVR", "NESTLEIND", "BRITANNIA", "TATACONSUM", "DABUR", "MARICO",
    "COLPAL", "GODREJCP",
    "ASIANPAINT", "BERGEPAINT", "KANSAINER",
    "PIDILITIND", "ASTRAL", "FINPIPE",
    "ULTRACEMCO", "AMBUJACEM", "SHREECEM", "DALBHARAT",
    "ABB", "SIEMENS", "CUMMINSIND", "HAVELLS", "POLYCAB", "KEI",
    "DIXON", "AMBER", "SYRMA",
    "DEEPAKNTR", "AARTIIND", "NAVINFLUOR", "SRF",
    "ADANIPORTS", "CONCOR"
]
