# Expanded Momentum Universe (Excluding Banks)
MOMENTUM_LIST = [
    # --- IT ---
    "TCS", "INFY", "WIPRO", "HCLTECH", "TECHM", "LTIM", "MPHASIS", "COFORGE", "PERSISTENT", "KPITTECH",
    # --- AUTO ---
    "MARUTI", "TATAMOTORS", "M&M", "EICHERMOT", "HEROMOTOCO", "BAJAJ-AUTO", "ASHOKLEY", "TVSMOTOR", "BHARATFORG", "BALKRISIND",
    # --- PHARMA ---
    "SUNPHARMA", "DRREDDY", "CIPLA", "DIVISLAB", "APOLLOHOSP", "LUPIN", "ALKEM", "AUROPHARMA", "ZYDUSLIFE", "GLENMARK", "BIOCON",
    # --- ENERGY & POWER ---
    "RELIANCE", "ONGC", "NTPC", "POWERGRID", "COALINDIA", "BPCL", "TATAPOWER", "GAIL", "ADANIGREEN", "ADANITRANS",
    # --- METALS ---
    "JSWSTEEL", "TATASTEEL", "HINDALCO", "JINDALSTEL", "SAIL", "NMDC", "VEDL", "HINDZINC",
    # --- FMCG ---
    "HINDUNILVR", "ITC", "NESTLEIND", "BRITANNIA", "TATACONSUM", "DABUR", "MARICO", "COLPAL", "GODREJCP", "VBL",
    # --- CONSUMER DURABLES ---
    "TITAN", "ASIANPAINT", "BERGEPAINT", "HAVELS", "POLYCAB", "DIXON", "AMBER", "VOLTAS",
    # --- CHEMICALS ---
    "PIDILITIND", "SRF", "DEEPAKNTR", "AARTIIND", "NAVINFLUOR", "TATACHEM", "COROMANDEL",
    # --- CEMENT ---
    "ULTRACEMCO", "GRASIM", "AMBUJACEM", "SHREECEM", "ACC", "DALBHARAT",
    # --- INFRA / LOGISTICS ---
    "ADANIPORTS", "CONCOR", "DLF", "L&T", "GMRINFRA", "IRCTC", "HAL", "BEL"
]

NIFTY50 = MOMENTUM_LIST # Backward compatibility for screener.py fallback

